name: Terraform CI/CD

on:
    pull_request:
        paths:
            - 'modules/**'
            - 'envs/**'
    workflow_dispatch:

jobs:
    plan:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.6.6

            - name: Terraform Init
              working-directory: ./envs/prod
              run: terraform init

            - name: Terraform Format Check
              working-directory: ./envs/prod
              run: terraform fmt -recursive -check

            - name: Terraform Validate
              working-directory: ./envs/prod
              run: terraform validate

            - name: Terraform Plan
              working-directory: ./envs/prod
              run: terraform plan
    
    apply:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.6.6

            - name: Terraform Init
              working-directory: ./envs/prod
              run: terraform init

            - name: Terraform Apply
              working-directory: ./envs/prod
              run: terraform apply -auto-approve